server:
  port: 10010
spring:
  application:
    name: rabbitmq888
  rabbitmq:
    host: 你自己的ip
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 16
rabbitmq-config:
  exchange: exchange666
  routingKey: routing666
