server:
  port: 10001
spring:
  application:
    name: zuul
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8989/eureka/
zuul:
  routes:
    ribbo:
      path: /api-ribbon/**
      serviceId: RIBBON
    feign:
      path: /api-feign/**
      serviceId: FEIGN
