server:
  port: 8989
spring:
  application:
    name: eurka-server
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://localhost:8989/eureka/