server:
  port: 9698
spring:
  application:
    name: ribbon
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8989/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'